MedicalApparatusManage/Controllers/SysRoleResourceController.cs
using MedicalApparatusManage.Domain;
using MedicalApparatusManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedicalApparatusManage.Controllers
{
    public class SysRoleResourceController : Controller
    {
        public int resultCount = 0; // 总条数 

        [CheckLogin()]
        public ActionResult Index(SysRoleResourceModels evalModel)
        {
            try
            {
                evalModel.currentPage = int.Parse(Request["pageNum"].ToString());
            }
            catch { }
            string order = "";
            try
            {
                order = Request["orderField"].ToString();
            }
            catch { }

            if (order.Trim() == "${param.orderField}")
            {
                order = "";
            }
            int pagesize = Convert.ToInt32(evalModel.pageSize);
            int pagecount = Convert.ToInt32(evalModel.pagecount);
            int currentPage = Convert.ToInt32(evalModel.currentPage);
            evalModel.DataModel = evalModel.DataModel ?? new SysRoleResource();
            evalModel.DataList = SysRoleResourceDomain.GetInstance().PageSysRoleResource(evalModel.DataModel, evalModel.StartTime, evalModel.EndTime, currentPage, pagesize, out pagecount, out resultCount);
            evalModel.resultCount = resultCount;
            return View("~/Views/SysRoleResource/Index.cshtml", evalModel);
        }

        [CheckLogin()]
        public ActionResult Save(System.Int32 id, string tag)
        {
            SysRoleResourceModels model = new SysRoleResourceModels();
            model.DataModel = new SysRoleResource();
            if (id != 0)
            {
                model.DataModel = SysRoleResourceDomain.GetInstance().GetModelById(id);
            }
            model.Tag = tag;
            return View("~/Views/SysRoleResource/Save.cshtml", model);
        }

        [HttpPost]
        [CheckLogin()]
        public void Save(SysRoleResourceModels model)
        {
            int result = 0;
            try
            {
                if (model.Tag == "Add")
                {
                    result = SysRoleResourceDomain.GetInstance().AddModel(model.DataModel);
                }
                else if (model.Tag == "Edit")
                {
                    result = SysRoleResourceDomain.GetInstance().UpdateModel(model.DataModel, model.DataModel.AuthorId);
                }

            }
            catch { }
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"closeCurrentReloadTab\",\"forwardUrl\":\"/SysRoleResource/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }

        [HttpPost]
        [CheckLogin()]
        public void Delete(System.Int32 id)
        {
            int result = SysRoleResourceDomain.GetInstance().DeleteModelById(id);
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"forward\",\"forwardUrl\":\"/SysRoleResource/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }
    }
}

MedicalApparatusManage/Views/SysRoleResource/Index.cshtml
@model MedicalApparatusManage.Models.SysRoleResourceModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SysRoleResource</title>
</head>
<body>
    <div id="pageContent">
        @*<div class="pageHeader" style="hight: 80px;">
                @using (Html.BeginForm("Index", "SysRoleResource", FormMethod.Post, new
                {
                    name = "formSerachMA",
                    id = "formSerachMA",
                    onsubmit = "return navTabSearch(this);"

                }))
                {
                    <div class="searchBar">
                        <table class="searchContent">
                            <tr>
                                <td>
                                    开始日期:
                                </td>
                                <td>
                                    @{ string strStart = Model.StartTime.HasValue ? Model.StartTime.Value.ToString("yyyy/MM/dd") : "";
                                        string strEnd = Model.EndTime.HasValue ? Model.EndTime.Value.ToString("yyyy/MM/dd") : "";
                                    }
                                    <input id="StartDate" name="StartTime" class="Wdate" type="text" value="@strStart"
                                           onfocus="WdatePicker({ dateFmt: 'yyyy/MM/dd', maxDate: '#F{$dp.$D(\'EndDate\')}' })" />
                                </td>
                                <td>
                                    结束日期:
                                </td>
                                <td>
                                    <input id="EndDate" name="EndTime" class="Wdate" type="text" value="@strEnd"
                                           onfocus="WdatePicker({ dateFmt: 'yyyy/MM/dd', minDate: '#F{$dp.$D(\'StartDate\')}' })" />
                                </td>

                                <td>
                                    <ul>
                                        <li>
                                            <div class="buttonActive">
                                                <div class="buttonContent">
                                                    <button type="submit" id="Button1" name="btnSerachOl">
                                                        检索
                                                    </button>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        </table>
                    </div>
                                        }
            </div>*@
        <div class="panelBar" id="EntLimitMenu">
            <ul class="toolBar">
                <li><a class="add" href="/SysRoleResource/Save/0/Add" target="dialog" mask="true" title="新增" width="1050" height="500"><span>新增</span></a></li>
                <li> <a class="edit" href="/SysRoleResource/Save/{sid_user}/Edit" target="dialog" mask="true" title="修改" width="1050" height="500"><span>修改</span></a></li>
                <li><a class="delete" href="/SysRoleResource/Delete/{sid_user}" target="ajaxTodo" title="确定删除吗?" mask="true"><span>删除</span></a></li>
                <li><a class="icon" href="/SysRoleResource/Save/{sid_user}/Details" target="dialog" mask="true" width="1050" height="500"><span>查看详情</span></a></li>
            </ul>
        </div>
        <table width="100%" layouth="112" class="table" id="SysRoleResourceTable">
            <thead>
                <tr>
                    <th>
                        RoleId
                    </th>
                    <th>
                        ResourceId
                    </th>
                    <th>
                        Authorized
                    </th>
                    <th>
                        Remark
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.DataList)
                {
                    <tr target="sid_user" rel="@item.AuthorId">
                        <td>@item.RoleId</td>
                        <td>@item.ResourceId</td>
                        <td>@item.Authorized</td>
                        <td>@item.Remark</td>
                    </tr>
                }
            </tbody>
        </table>
        <form id="pagerForm" method="post" onsubmit="return navTabSearch(this);">
            <input type="hidden" name="pageNum" id="pageNum" />
            @Html.HiddenFor(m => m.pageSize, new { name = "numPerPage", id = "numPerPage" })
            <input type="hidden" name="totalCount" id="totalCount" />
            @Html.HiddenFor(m => m.SortCol, new { name = "SortCol_OP", id = "SortCol_OP" })
            @Html.HiddenFor(m => m.SortKey, new { name = "SortKey_OP", id = "SortKey_OP" })
            @Html.HiddenFor(m => m.StartTime, new { name = "StartTime" })
            @Html.HiddenFor(m => m.EndTime, new { name = "EndTime" })
            <input type="hidden" name="orderField" value="${param.orderField}" />
            <input type="hidden" name="orderDirection" value="${param.orderDirection}" />
        </form>
        <div class="panelBar">
            <div class="pages">
                <span style="width: 35px;">显示</span>
                @{
                    string[] sL = { "10", "20", "30", "50", "100", "500", "1000", "5000" };
                    List<SelectListItem>
                                list = new List<SelectListItem>
                                    ();
                    foreach (string s in sL)
                    {
                        list.Add(new SelectListItem { Text = s, Value = s });
                    }
                    @Html.DropDownListFor(m => m.pageSize, list, new { name = "numPerPage", id = "numPerPage", onchange = "navTabPageBreak({numPerPage:this.value});" });
                    <span>
                        条，共<label>@Model.resultCount</label>
                        条
                    </span>

                }
            </div>
            <div class="pagination" targettype="navTab" totalcount="@Model.resultCount"
                 numperpage="@Model.pageSize" pagenumshown="@Model.pagecount"
                 currentpage="@Model.currentPage">
            </div>
        </div>
    </div>
</body>
</html>

MedicalApparatusManage/Views/SysRoleResource/Save.cshtml
@model MedicalApparatusManage.Models.SysRoleResourceModels
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Save</title>
    <script type="text/javascript" language="javascript">
        $(function () {
            var tag = $("#Tag").val();
            if (tag == "Details") {
                $("form input").prop("readonly", true);
                $("#divSave").hide();
            }
        });
        function Save() {
            var elements = document.forms['formSysRoleResource'];
            var bl = validateCallback(elements);
            if (bl) {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "/SysRoleResource/Save",
                    data: $("#formSysRoleResource").serializeArray(),
                    success: dialogAjaxDone
                });
            }
        };
    </script>
</head>
<body>
    <div class="pageContent">
        <form id="formSysRoleResource" method="post" onsubmit="return false;" class="pageForm required-validate-noalert">
            <div class="pageFormContent" layouth="58">
                @Html.HiddenFor(m => m.Tag, new { ID = "Tag", Name = "Tag" })
                @Html.HiddenFor(m=>m.DataModel.AuthorId,new { Name = "DataModel.AuthorId" }) %>
            <div class="unit">
                <label>
                    RoleId：</label>
                @Html.TextBoxFor(m => m.DataModel.RoleId, new {name = "RoleId" })%>
            </div>
            <div class="unit">
                <label>
                    ResourceId：</label>
                @Html.TextBoxFor(m => m.DataModel.ResourceId, new {name = "ResourceId" })%>
            </div>
            <div class="unit">
                <label>
                    Authorized：</label>
                @Html.TextBoxFor(m => m.DataModel.Authorized, new {name = "Authorized" })%>
            </div>
            <div class="unit">
                <label>
                    Remark：</label>
                @Html.TextBoxFor(m => m.DataModel.Remark, new {name = "Remark" })%>
            </div>
            </div>
            <div class="formBar">
                <ul>
                    <li>
                        <div class="button" id="divSave">
                            <div class="buttonContent">
                                <button value="保存" onclick="Save();">
                                    保存
                                </button>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="button">
                            <div class="buttonContent">
                                <button value="取消" class="close">
                                    取消
                                </button>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</body>
</html>