MedicalApparatusManage/Controllers/T_THDController.cs
using MedicalApparatusManage.Common;
using MedicalApparatusManage.Domain;
using MedicalApparatusManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace MedicalApparatusManage.Controllers
{
    public class T_THDController : Controller
    {
        public int resultCount = 0; // 总条数 

        [CheckLogin()]
        public ActionResult Index(T_THDModels evalModel)
        {
            try
            {
                evalModel.currentPage = int.Parse(Request["pageNum"].ToString());
            }
            catch { }
            string order = "";
            try
            {
                order = Request["orderField"].ToString();
            }
            catch { }

            if (order.Trim() == "${param.orderField}")
            {
                order = "";
            }
            int pagesize = Convert.ToInt32(evalModel.pageSize);
            int pagecount = Convert.ToInt32(evalModel.pagecount);
            int currentPage = Convert.ToInt32(evalModel.currentPage);
            evalModel.DataModel = evalModel.DataModel ?? new T_THD();

            if (Request["strTHMC"] != null)
            {
                string str = Request["strTHMC"].ToString();
                if (!String.IsNullOrEmpty(str))
                {
                    evalModel.DataModel.THMC = str;
                }
            }

            if (Request["strTHSQPerson"] != null)
            {
                string str = Request["strTHSQPerson"].ToString();
                if (!String.IsNullOrEmpty(str))
                {
                    evalModel.DataModel.SQR = str;
                }
                ViewData["strTHSQPerson"] = str;
            }
            //获取本企业下的人员列表
            SysUser UserModel = Session["UserModel"] as SysUser;
            T_Person person = new T_Person();
            person.PsQYID = (int)UserModel.UserCompanyID;
            ViewBag.Persons = new SelectList(T_PersonDomain.GetInstance().GetAllT_Person(person), "PsMZ", "PsMZ");

            evalModel.DataList = T_THDDomain.GetInstance().PageT_THD(evalModel.DataModel, evalModel.StartTime, evalModel.EndTime, currentPage, pagesize, out pagecount, out resultCount).ToList();
            evalModel.resultCount = resultCount;
            return View("~/Views/T_THD/Index.cshtml", evalModel);
        }

        [CheckLogin()]
        public ActionResult Save(System.Int32 id, string tag)
        {
            //加载企业列表
            T_SupQYModels supmode = new T_SupQYModels();
            supmode.DataModel = supmode.DataModel ?? new T_SupQY();
            supmode.DataList = T_SupQYDomain.GetInstance().GetAllT_SupQY(supmode.DataModel).Where(p => p.SupStatus == 1).ToList();
            ViewData["SupID"] = new SelectList(supmode.DataList, "SupID", "SupMC");

            Expression<Func<T_YSD, bool>> where = PredicateBuilder.True<T_YSD>();
            where = where.And(p => p.IsTHFinish != 1);
            var yslist = T_YSDDomain.GetInstance().GetAllModels<int>(where);
            ViewData["YSD"] = new SelectList(yslist, "YSID", "YSDH");

            T_THDModels model = new T_THDModels();
            model.DataModel = new T_THD();
            var CurUser = Session["UserModel"] as SysUser;
            //获取本企业下的人员列表
            T_Person person = new T_Person();
            if (CurUser.UserCompanyID != null)
                person.PsQYID = (int)CurUser.UserCompanyID;
            ViewBag.Persons = new SelectList(T_PersonDomain.GetInstance().GetAllT_Person(person), "PsMZ", "PsMZ");

            //加载仓库列表
            T_CKModels ckmode = new T_CKModels();
            ckmode.DataModel = ckmode.DataModel ?? new T_CK();
            ckmode.DataList = T_CKDomain.GetInstance().GetAllT_CK(ckmode.DataModel);
            ViewData["CK"] = new SelectList(ckmode.DataList, "CKID", "CKMC");

            if (id != 0)
            {
                model.DataModel = T_THDDomain.GetInstance().GetModelById(id);
                model.THMXList = T_THMXDomain.GetInstance().GetT_THMXByYsid(id);
                if (model.DataModel.YSID != null && model.DataModel.YSID != 0)
                {
                    var temp = T_YSDDomain.GetInstance().GetModelById(model.DataModel.YSID);
                    if (temp != null)
                        model.YSDH = temp.YSDH;
                }
            }
            else
            {
                model.DataModel.THDH = T_THDDomain.GetInstance().GetTHOrderNum("TH", CurUser);
                model.DataModel.THCJR = CurUser.UserAccount;
                model.DataModel.THCJRQ = DateTime.Now;
            }
            model.Tag = tag;
            model.RoleCode = GetRoleCode();
            return View("~/Views/T_THD/Save.cshtml", model);
        }

        [HttpPost]
        [CheckLogin()]
        public void Save(T_THDModels model)
        {
            int result = 0;
            try
            {
                if (model.Tag == "Add")
                {
                    model.DataModel.FLAG = 1;
                    model.DataModel.ISSH = 0;

                    var temp = T_THDDomain.GetInstance().GetAllModels<string>(p => p.THDH == model.DataModel.THDH).FirstOrDefault();
                    if (temp != null && temp.THID != 0)
                    {
                        var CurUser1 = Session["UserModel"] as SysUser;
                        model.DataModel.THDH = T_THDDomain.GetInstance().GetTHOrderNum("TH", CurUser1);
                    }

                    result = T_THDDomain.GetInstance().AddModel(model.DataModel);
                }
                else if (model.Tag == "Edit")
                {
                    model.DataModel.FLAG = 1;
                    result = T_THDDomain.GetInstance().UpdateModel(model.DataModel, model.DataModel.THID);
                }

            }
            catch { }
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"closeCurrentReloadTab\",\"forwardUrl\":\"/T_THD/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }

        [HttpPost]
        [CheckLogin()]
        public void XSSave(T_THDModels model)
        {
            int result = 0;
            try
            {
                if (model.Tag == "Add")
                {
                    model.DataModel.FLAG = 2;
                    result = T_THDDomain.GetInstance().AddModel(model.DataModel);
                }
                else if (model.Tag == "Edit")
                {
                    model.DataModel.FLAG = 2;
                    result = T_THDDomain.GetInstance().UpdateModel(model.DataModel, model.DataModel.THID);
                }

            }
            catch { }
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"closeCurrentReloadTab\",\"forwardUrl\":\"/T_THD/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }

        [HttpPost]
        [CheckLogin()]
        public void Delete(System.Int32 id)
        {
            var temp = T_THDDomain.GetInstance().GetModelById(id);
            if (temp != null)
            {
                if (temp.ISSH == 1)
                {
                    Response.Write("{\"statusCode\":\"300\", \"message\":\"已审批通过的数据不能删除！\"}");
                    return;
                }
            }
            int result = T_THDDomain.GetInstance().Delete(id);
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"forward\",\"forwardUrl\":\"/T_THD/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }
        [HttpPost]
        [CheckLogin()]
        public void through(T_THDModels model, int id)
        {
            int result = 0;
            try
            {
                Int32 cgid = model.DataModel.THID;
                result = T_THDDomain.GetInstance().Sh(cgid, id);
                if (id == 1 && model.DataModel.IsFinish == 1 && model.DataModel.YSID != 0)  //IsFinish=1表示该退货单对应的验收单已经完结
                {
                    T_YSDDomain.GetInstance().UpdateFinish((int)model.DataModel.YSID);
                }
            }
            catch { }
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"closeCurrentReloadTab\",\"forwardUrl\":\"/T_THD/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }
        private string GetRoleCode()
        {
            return Session["RoleCode"] == null ? "" : Session["RoleCode"].ToString();
        }
        [CheckLogin()]
        public ActionResult THMXTable(System.Int32 id, string thdh, int canEdit, int isSH)
        {
            T_THDModels model = new T_THDModels();
            if (id != 0)
            {
                model.THMXList = T_THMXDomain.GetInstance().GetT_THMXBythid(id);
            }
            else
            {
                model.THMXList = T_THMXDomain.GetInstance().GetT_THMXBythdh(thdh);
            }
            ViewData["canEdit"] = canEdit;
            model.RoleCode = GetRoleCode();
            model.DataModel = new T_THD();
            model.DataModel.ISSH = isSH;
            //model.DataModel.THID = id;
            return View("~/Views/T_THD/THMXTable.cshtml", model);
        }
    }
}

MedicalApparatusManage/Views/T_THD/Index.cshtml
@model MedicalApparatusManage.Models.T_THDModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>退货单</title>
    <script type="text/javascript" language="javascript">
        $(function () {
            $("#strTHSQPerson", $("#formSerachMATHD")).chosen({
                search_contains: true
            });
        });
    </script>
</head>
<body>
    <div id="pageContent">
        <div class="pageHeader" style="hight: 80px;">
            @using (Html.BeginForm("Index", "T_THD", FormMethod.Post, new
            {
                name = "formSerachMA",
                id = "formSerachMATHD",
                onsubmit = "return navTabSearch(this);"

            }))
            {
                <div class="searchBar">
                    <table class="searchContent">
                        <tr>
                            <td>
                                退货单名称:
                            </td>
                            <td>
                                @Html.TextBox("strTHMC", Model.DataModel.THMC)
                            </td>
                            <td>
                                申请人:
                            </td>
                            <td>
                                @Html.DropDownList("strTHSQPerson", ViewBag.Persons as SelectList, "请选择", new { Value = ViewData["strTHSQPerson"], id = "strTHSQPerson", style = "width:150px;" })
                            </td>
                            <td>
                                申请日期:
                            </td>
                            <td>
                                @{ string strStart = Model.StartTime.HasValue ? Model.StartTime.Value.ToString("yyyy/MM/dd") : "";
                                    string strEnd = Model.EndTime.HasValue ? Model.EndTime.Value.ToString("yyyy/MM/dd") : "";
                                }
                                <input id="StartDate" name="StartTime" class="Wdate" type="text" autocomplete="off" value="@strStart"
                                       onfocus="WdatePicker({ dateFmt: 'yyyy/MM/dd', maxDate: '#F{$dp.$D(\'EndDate\')}' })" />
                            </td>
                            <td>
                                至
                            </td>
                            <td>
                                <input id="EndDate" name="EndTime" class="Wdate" type="text" autocomplete="off" value="@strEnd"
                                       onfocus="WdatePicker({ dateFmt: 'yyyy/MM/dd', minDate: '#F{$dp.$D(\'StartDate\')}' })" />
                            </td>
                            <td>
                                <ul>
                                    <li>
                                        <div class="buttonActive">
                                            <div class="buttonContent">
                                                <button type="submit" id="Button1" name="btnSerachOl">
                                                    检索
                                                </button>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    </table>
                </div>
            }
        </div>
        <div class="panelBar" id="EntLimitMenu">
            <ul class="toolBar">
                <li><a class="add" href="/T_THD/Save/0/Add" target="dialog" mask="true" title="新增" width="1050" height="500"><span>新增</span></a></li>
                @*<li> <a class="edit" href="/T_THD/Save/{sid_user}/Edit" target="dialog" mask="true" title="修改" width="1050" height="500"><span>修改</span></a></li>*@
                <li><a class="delete" href="/T_THD/Delete/{sid_user}" target="ajaxTodo" title="确定删除吗?" mask="true"><span>删除</span></a></li>
                <li><a class="icon" href="/T_THD/Save/{sid_user}/Edit" target="dialog" mask="true" width="1050" height="500"><span>查看详情</span></a></li>
            </ul>
        </div>
        <table width="100%" layouth="112" class="table" id="T_THDTable">
            <thead>
                <tr>
                    <th>
                        退货单名称
                    </th>
                    <th>
                        退货单号
                    </th>
                    <th>
                        验收单号
                    </th>
                    <th>
                        申请人
                    </th>
                    <th>
                        申请日期
                    </th>
                    <th>
                        退货原因
                    </th>
                    @*<th>
                            审核人
                        </th>
                        <th>
                            审核日期
                        </th>
                        <th>
                            审核意见
                        </th>*@
                    <th>
                        备注
                    </th>
                    <th>
                        审批状态
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.DataList != null)
                {
                    foreach (var item in Model.DataList)
                    {
                        <tr target="sid_user" rel="@item.THID">
                            <td>@item.THMC</td>
                            <td>@item.THDH</td>
                            <td>@((item.T_YSD != null && !string.IsNullOrEmpty(item.T_YSD.YSDH)) ? item.T_YSD.YSDH : "")</td>
                            <td>@item.SQR</td>
                            @{ if (item.SQRQ == null)
                                {
                                    <td></td>
                                }
                                else
                                {
                                    <td>@item.SQRQ.Value.ToString("yyyy/MM/dd")</td>
                                }
                            }
                            <td>@item.THYY</td>
                            @*<td>@item.SHR</td>
                                <td>@item.SHRQ</td>
                                <td>@item.SHYJ</td>*@
                            <td>@item.BZ</td>
                            @{
                                switch (item.ISSH)
                                {
                                    case 0:
                                        <td style="background-color:deepskyblue;">未审批</td>; break;
                                    case 1:
                                        <td style="background-color:limegreen;">审批通过</td>; break;
                                    case 2:
                                        <td style="background-color:orangered;">审批未通过</td> ; break;
                                    default:
                                        <td></td>; break;
                                }}
                        </tr>
                    }
                }
            </tbody>
        </table>
        <form id="pagerForm" method="post" onsubmit="return navTabSearch(this);">
            <input type="hidden" name="pageNum" id="pageNum" />
            @Html.HiddenFor(m => m.pageSize, new { name = "numPerPage", id = "numPerPage" })
            <input type="hidden" name="totalCount" id="totalCount" />
            @Html.HiddenFor(m => m.SortCol, new { name = "SortCol_OP", id = "SortCol_OP" })
            @Html.HiddenFor(m => m.SortKey, new { name = "SortKey_OP", id = "SortKey_OP" })
            @Html.HiddenFor(m => m.StartTime, new { name = "StartTime" })
            @Html.HiddenFor(m => m.EndTime, new { name = "EndTime" })
            <input type="hidden" name="orderField" value="${param.orderField}" />
            <input type="hidden" name="orderDirection" value="${param.orderDirection}" />
        </form>
        <div class="panelBar">
            <div class="pages">
                <span style="width: 35px;">显示</span>
                @{
                    string[] sL = { "10", "20", "30", "50", "100", "500", "1000", "5000" };
                    List<SelectListItem>
                                                    list = new List<SelectListItem>
                                                        ();
                    foreach (string s in sL)
                    {
                        list.Add(new SelectListItem { Text = s, Value = s });
                    }
                    @Html.DropDownListFor(m => m.pageSize, list, new { name = "numPerPage", id = "numPerPage", onchange = "navTabPageBreak({numPerPage:this.value});" });
                    <span>
                        条，共<label>@Model.resultCount</label>
                        条
                    </span>

                }
            </div>
            <div class="pagination" targettype="navTab" totalcount="@Model.resultCount"
                 numperpage="@Model.pageSize" pagenumshown="@Model.pagecount"
                 currentpage="@Model.currentPage">
            </div>
        </div>
    </div>
</body>
</html>

MedicalApparatusManage/Views/T_THD/THMXTable.cshtml
@model MedicalApparatusManage.Models.T_THDModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>THMXTable</title>
    <script type="text/javascript" language="javascript">
        function deleteTHMX(obj) {
            alertMsg.confirm("确定要删除么？", {
                okCall: function () {
                    var guid1 = obj.getAttribute("name");
                    $.post("/T_THMX/Delete", { id: guid1 }, function (data) {
                        if (data.statusCode == "200") {
                            $("#thmxBox").loadUrl("/T_THD/THMXTable", { id: 0, thdh: $("#THDH").val(), canEdit: 1, isSH: $("#hdISSH").val() });
                            alertMsg.correct('删除成功！');
                        } else {
                            alertMsg.error('删除失败！');
                        }
                    }, "json");
                }
            });
        }
    </script>
</head>
<body>
    <div>
        <table width="100%" layouth="280" class="table">
            <thead>
                <tr>
                    <th>
                        供货企业
                    </th>
                    <th>
                        产品编号
                    </th>
                    <th>
                        产品名称
                    </th>
                    <th>
                        生产企业
                    </th>
                    <th>
                        产品规格
                    </th>
                    <th>
                        产品型号
                    </th>
                    <th>
                        包装单位
                    </th>
                    <th>
                        产品数量
                    </th>
                    <th>
                        产品批号
                    </th>
                    <th>
                        生产日期
                    </th>
                    <th>
                        有效期
                    </th>
                    <th>
                        许可证号
                    </th>
                    <th>
                        注册证号
                    </th>
                    <th>
                        库房
                    </th>
                    <th>
                        库管
                    </th>
                    @{if (Model.DataModel.ISSH != 1)
                        {
                            <th type="del">
                                操作
                            </th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model.THMXList != null)
                {
                    foreach (var item in Model.THMXList)
                    {
                        <tr target="sid_user">
                            <td>@(item.T_YLCP != null && item.T_YLCP.T_SupQY != null && !string.IsNullOrEmpty(item.T_YLCP.T_SupQY.SupMC) ? item.T_YLCP.T_SupQY.SupMC : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPBH) ? item.T_YLCP.CPBH : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPMC) ? item.T_YLCP.CPMC : "")</td>
                            <td>@(item.T_YLCP != null && item.T_YLCP.T_SupQY1 != null && !string.IsNullOrEmpty(item.T_YLCP.T_SupQY1.SupMC) ? item.T_YLCP.T_SupQY1.SupMC : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPGG) ? item.T_YLCP.CPGG : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPXH) ? item.T_YLCP.CPXH : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPDW) ? item.T_YLCP.CPDW : "")</td>
                            <td>@item.CPNUM</td>
                            <td>@item.CPPH</td>
                            <td>@(item.CPSCRQ.HasValue ? item.CPSCRQ.Value.ToString("yyyy/MM/dd") : "")</td>
                            <td>@(item.CPYXQ.HasValue ? item.CPYXQ.Value.ToString("yyyy/MM/dd") : "")</td>
                            <td>@(item.T_YLCP.T_SupQY1 != null && !string.IsNullOrEmpty(item.T_YLCP.T_SupQY1.SupXKZBH) ? item.T_YLCP.T_SupQY1.SupXKZBH : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPZCZ) ? item.T_YLCP.CPZCZ : "")</td>
                            <td>@(item.T_CK != null && !string.IsNullOrEmpty(item.T_CK.CKMC) ? item.T_CK.CKMC : "")</td>
                            <td>@(item.T_CK != null && !string.IsNullOrEmpty(item.T_CK.CKGLY) ? item.T_CK.CKGLY : "")</td>
                            @{if (Model.DataModel.ISSH != 1)
                                {
                                    <td>
                                        <a href="javascript:void(0)" name="@item.MXID" class="btnDel" onclick="deleteTHMX(this);">删除</a>
                                    </td>
                                }
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
        <input type="hidden" value="@Model.DataModel.ISSH" id="hdISSH" />
    </div>
</body>
</html>

MedicalApparatusManage/Views/T_THD/XSSave.cshtml
@model MedicalApparatusManage.Models.T_THDModels
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Save</title>
    <script type="text/javascript" language="javascript">
        $(function () {
            var tag = $("#Tag").val();
            if (tag == "Details") {
                $("form input").prop("readonly", true);
                $("#divSave").hide();
            }
        });
        function Save() {
            var elements = document.forms['formT_SXTHD'];
            var bl = validateCallback(elements);
            if (bl) {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "/T_THD/XSSave",
                    data: $("#formT_SXTHD").serializeArray(),
                    success: dialogAjaxDone
                });
            }
        };
    </script>
</head>
<body>
    <div class="pageContent">
        <form id="formT_SXTHD" method="post" onsubmit="return false;" class="pageForm required-validate-noalert">
            <div class="pageFormContent" layouth="58">
                @Html.HiddenFor(m => m.Tag, new { ID = "Tag", Name = "Tag" })
                @Html.HiddenFor(m => m.DataModel.THID, new { Name = "DataModel.THID" })
                @Html.HiddenFor(m => m.DataModel.FLAG, new { Name = "DataModel.FLAG" })
                <div class="unit">
                    <label>
                        申请人：
                    </label>
                    @Html.TextBoxFor(m => m.DataModel.SQR, new { name = "SQR" })
                </div>
                <div class="unit">
                    <label>
                        申请日期：
                    </label>
                    @Html.TextBoxFor(m => m.DataModel.SQRQ, new { name = "SQRQ", @class = "Wdate", onfocus = "WdatePicker({ dateFmt: 'yyyy/MM/dd' })" })
                </div>
                <div class="unit">
                    <label>
                        退货原因：
                    </label>
                    @Html.TextBoxFor(m => m.DataModel.THYY, new { name = "THYY" })
                </div>
                <div class="unit">
                    <label>
                        审核人：
                    </label>
                    @Html.TextBoxFor(m => m.DataModel.SHR, new { name = "SHR" })
                </div>
                <div class="unit">
                    <label>
                        审核日期：
                    </label>
                    @Html.TextBoxFor(m => m.DataModel.SHRQ, new { name = "SHRQ", @class = "Wdate", onfocus = "WdatePicker({ dateFmt: 'yyyy/MM/dd' })" })
                </div>
                <div class="unit">
                    <label>
                        审核意见：
                    </label>
                    @Html.TextBoxFor(m => m.DataModel.SHYJ, new { name = "SHYJ" })
                </div>
                @*<div class="unit">
                        <label>
                            标识：
                        </label>
                        @Html.TextBoxFor(m => m.DataModel.FLAG, new { name = "FLAG" })
                    </div>*@
                <div class="unit">
                    <label>
                        备注：
                    </label>
                    @Html.TextBoxFor(m => m.DataModel.BZ, new { name = "BZ" })
                </div>
            </div>
            <div class="formBar">
                <ul>
                    <li>
                        <div class="button" id="divSave">
                            <div class="buttonContent">
                                <button value="保存" onclick="Save();">
                                    保存
                                </button>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="button">
                            <div class="buttonContent">
                                <button value="取消" class="close">
                                    取消
                                </button>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</body>
</html>