MedicalApparatusManage/Controllers/T_CKMXController.cs
using MedicalApparatusManage.Domain;
using MedicalApparatusManage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MedicalApparatusManage.Controllers
{
    public class T_CKMXController : Controller
    {
        public int resultCount = 0; // 总条数 

        [CheckLogin()]
        public ActionResult Index(T_CKMXModels evalModel, string id)
        {
            try
            {
                evalModel.currentPage = int.Parse(Request["pageNum"].ToString());
            }
            catch { }
            string order = "";
            try
            {
                order = Request["orderField"].ToString();
            }
            catch { }

            if (order.Trim() == "${param.orderField}")
            {
                order = "";
            }
            ViewBag.CKDID = id;
            int pagesize = Convert.ToInt32(evalModel.pageSize);
            int pagecount = Convert.ToInt32(evalModel.pagecount);
            int currentPage = Convert.ToInt32(evalModel.currentPage);
            evalModel.DataModel = evalModel.DataModel ?? new T_CKMX();
            evalModel.DataList = T_CKMXDomain.GetInstance().PageT_CKMX(evalModel.DataModel, evalModel.StartTime, evalModel.EndTime, currentPage, pagesize, out pagecount, out resultCount).Where(p => p.CKDID == int.Parse(id)).ToList();
            evalModel.resultCount = resultCount;
            ViewData["ParaStr"] = ExportExcelPR(int.Parse(id));
            return View("~/Views/T_CKMX/Index.cshtml", evalModel);
        }

        [CheckLogin()]
        public ActionResult Save(System.Int32 id, string tag)
        {
            T_CKMXModels model = new T_CKMXModels();
            model.DataModel = new T_CKMX();
            Int32 did = id;
            if (tag != "Add")
            {
                model.DataModel = T_CKMXDomain.GetInstance().GetModelById(id);
                did = model.DataModel.CKDID ?? 0;
            }
            //加载仓库列表
            T_CKModels ckmode = new T_CKModels();

            ckmode.DataModel = ckmode.DataModel ?? new T_CK();

            ckmode.DataList = T_CKDomain.GetInstance().GetAllT_CK(ckmode.DataModel);

            ViewData["CK"] = new SelectList(ckmode.DataList, "CKID", "CKMC");

            //加载产品列表
            T_YLCPModels ylcpQymode = new T_YLCPModels();

            ylcpQymode.DataModel = ylcpQymode.DataModel ?? new T_YLCP();

            ylcpQymode.DataList = T_YLCPDomain.GetInstance().GetAllT_YLCP(ylcpQymode.DataModel).Where(p => p.CPStatus == Convert.ToInt32("1")).ToList();

            ViewData["YLCP"] = new SelectList(ylcpQymode.DataList, "CPID", "CPMC");

            //加载出库单列表
            T_CKDModels ckdQymode = new T_CKDModels();

            ckdQymode.DataModel = ckdQymode.DataModel ?? new T_CKD();

            T_CKD ckd = T_CKDDomain.GetInstance().GetModelById(did);
            ckdQymode.DataList = new List<T_CKD>();
            ckdQymode.DataList.Add(ckd);
            ViewData["CKD"] = new SelectList(ckdQymode.DataList, "CKID", "CKMC");



            //if (id != 0)
            //{
            //    model.DataModel = T_CKMXDomain.GetInstance().GetModelById(id);
            //}
            model.Tag = tag;
            return View("~/Views/T_CKMX/Save.cshtml", model);
        }

        [CheckLogin()]
        public void ExportExcel(System.Int32 id)
        {
            //接收需要导出的数据
            T_CKD ckdinfo = new T_CKD();

            List<T_CKD> list = T_CKDDomain.GetInstance().GetListModelById(id);
            if (list.Count > 0)
            {
                ckdinfo = list[0];
            }

            int xsqyid = ckdinfo.T_XSD.KHID ?? 0;

            T_CusQY cusqy = T_CusQYDomain.GetInstance().GetModelById(xsqyid);
            //客户企业名称
            string xsqyName = cusqy.CusMC;

            List<T_CKMX> ckmxList = T_CKMXDomain.GetInstance().GetListModelById(id);

            //命名导出表格的StringBuilder变量
            StringBuilder sHtml = new StringBuilder(string.Empty);
            //打印表头
            sHtml.Append("<table border=\"0\" width=\"100%\">");
            sHtml.Append("<tr height=\"40\"><td colspan=\"10\" align=\"center\" style='font-size:24px'><b>出库单" + "</b></td></tr>");
            sHtml.Append("<tr height=\"40\"><td colspan=\"8\" align=\"left\">购买单位：" + xsqyName + "</td><td align=\"right\">日期：" + DateTime.Now.ToString("yyyy-MM-dd") + "</td><td align=\"right\">单据编号：" + DateTime.Now.ToString("yyyyMMddHHmmssffff") + "</td></tr>");
            sHtml.Append("</table>");
            sHtml.Append("<table border=\"1\" width=\"100%\">");
            //sHtml.Append("<tr height=\"40\"><td colspan=\"10\" align=\"center\" style='font-size:24px'><b>出库单" + "</b></td></tr>");
            //sHtml.Append("<tr height=\"40\"><td colspan=\"8\" align=\"left\">&nbsp;购买单位：" + xsqyName + "</td><td align=\"right\">日期：" + DateTime.Now.ToString("yyyy-MM-dd") + "</td><td align=\"right\">单据编号：" + DateTime.Now.ToString("yyyyMMddHHmmssffff") + "</td></tr>");
            //打印列名
            sHtml.Append("<tr height=\"30\" align=\"center\" ><td>商品名称</td><td>规格</td><td>生产厂家</td><td>单位</td><td>数量</td><td>单价</td>"
                + "<td>金额</td><td>批号</td><td>生产日期</td><td>注册证号</td></tr>");

            //合计
            double total = 0.0;
            for (int i = 0; i < ckmxList.Count; i++)
            {
                T_CKMX ckmx = ckmxList[i];
                //产品名称
                string cpName = ckmx.T_YLCP.CPMC;
                //规格
                string cpGg = ckmx.T_YLCP.CPGG ?? "";
                //单位
                string cpDw = ckmx.T_YLCP.CPDW ?? "";
                //数量
                double cpDj = ckmx.CPNUM ?? 0;
                //生成批号
                string scPh = ckmx.T_YLCP.CPPH ?? "";
                //生产日期
                string scRq = "";
                if (ckmx.T_YLCP.CPSCSJ != null)
                {
                    scRq = ckmx.T_YLCP.CPSCSJ.Value.ToLongDateString();
                }

                //生产企业
                string cpScqy = ckmx.T_YLCP.CPSCQY ?? "";
                //单价
                double cpPrice = ckmx.T_YLCP.CPPrice ?? 0.0;
                //产品总价
                double rowTotal = cpDj * cpPrice;

                total = total + rowTotal;
                //注册证号
                string cpzczh = ckmx.T_YLCP.CPZCZ;

                sHtml.Append("<tr height=\"30\" align=\"center\"><td>" + cpName
    + "</td><td>" + cpGg + "</td><td>" + cpScqy
    + "</td><td>" + cpDw + "</td><td>" + cpDj.ToString()
    + "</td><td>" + cpPrice.ToString() + "</td><td>" + rowTotal.ToString() + "</td><td>" + scPh + "</td><td>" + scRq
    + "</td><td>" + cpzczh
    + "</td></tr>");
            }
            //循环读取List集合 
            for (int i = 0; i < list.Count; i++)
            {

            }
            //打印表尾
            sHtml.Append("<tr height=\"40\" align=\"center\"><td>合计：</td><td colspan=\"9\">" + total + "</td></tr>");
            sHtml.Append("</table>");
            sHtml.Append("<table  border=\"0\" width=\"100%\">");
            sHtml.Append("<tr height=\"40\" align=\"center\"><td colspan=\"7\" align=\"left\">制单人：&nbsp;&nbsp</td><td align=\"right\">审核人：&nbsp;&nbsp</td><td align=\"right\">发货人：&nbsp;&nbsp</td><td align=\"center\">销售员：&nbsp;&nbsp</td></tr>");
            sHtml.Append("</table>");
            //调用输出Excel表的方法
            ExportToExcel("application/vnd.ms-excel", "出库单.xls", sHtml.ToString());
        }

        [CheckLogin()]
        public void ExportToExcel(string FileType, string FileName, string ExcelContent)
        {
            System.Web.HttpContext.Current.Response.Charset = "GB2312";
            System.Web.HttpContext.Current.Response.ContentEncoding = System.Text.Encoding.GetEncoding("GB2312");
            System.Web.HttpContext.Current.Response.AppendHeader("Content-Disposition", "attachment;filename=" + HttpUtility.UrlEncode(FileName, System.Text.Encoding.GetEncoding("GB2312")).ToString());
            System.Web.HttpContext.Current.Response.ContentType = FileType;
            System.IO.StringWriter tw = new System.IO.StringWriter();
            System.Web.HttpContext.Current.Response.Output.Write(ExcelContent.ToString());
            System.Web.HttpContext.Current.Response.Flush();
            System.Web.HttpContext.Current.Response.End();
        }

        [CheckLogin()]
        public string ExportExcelPR(System.Int32 id)
        {
            //接收需要导出的数据
            T_CKD ckdinfo = new T_CKD();

            List<T_CKD> list = T_CKDDomain.GetInstance().GetListModelById(id);
            if (list.Count > 0)
            {
                ckdinfo = list[0];
            }

            int xsqyid = ckdinfo.T_XSD.KHID ?? 0;

            T_CusQY cusqy = T_CusQYDomain.GetInstance().GetModelById(xsqyid);
            //客户企业名称
            string xsqyName = cusqy.CusMC;

            List<T_CKMX> ckmxList = T_CKMXDomain.GetInstance().GetListModelById(id);

            //命名导出表格的StringBuilder变量
            StringBuilder sHtml = new StringBuilder(string.Empty);
            //打印表头
            sHtml.Append("<table border=\"0\" width=\"100%\">");
            sHtml.Append("<tr height=\"40\"><td colspan=\"10\" align=\"center\" style='font-size:24px'><b>出库单" + "</b></td></tr>");
            sHtml.Append("<tr height=\"40\"><td colspan=\"8\" align=\"left\">购买单位：" + xsqyName + "</td><td align=\"right\">日期：" + DateTime.Now.ToString("yyyy-MM-dd") + "</td><td align=\"right\">单据编号：" + DateTime.Now.ToString("yyyyMMddHHmmssffff") + "</td></tr>");
            sHtml.Append("</table>");
            sHtml.Append("<table border=\"1\" width=\"100%\">");
            //sHtml.Append("<tr height=\"40\"><td colspan=\"10\" align=\"center\" style='font-size:24px'><b>出库单" + "</b></td></tr>");

MedicalApparatusManage/Views/T_CKMX/CKMXTable.cshtml
@model MedicalApparatusManage.Models.T_CKDModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <script type="text/javascript" language="javascript">
        function deleteCKMX(obj) {
            alertMsg.confirm("确定要删除么？", {
                okCall: function () {
                    var guid1 = obj.getAttribute("name");
                    $.post("/T_CKMX/Delete", { Guid: guid1 }, function (data) {
                        if (data.statusCode == "200") {
                            $("#ckmxCkPageBox").loadUrl("/T_CKMX/CKMXTable", { id: 0, ckdh: $("#CKDH").val(), canEdit: 0 });
                            alertMsg.correct('删除成功！');
                        } else {
                            alertMsg.error('删除失败！');
                        }
                    }, "json");
                }
            });
        }
    </script>
</head>
<body>
    <div>
        <table width="100%" layouth="280" class="table">
            <thead>
                <tr>
                    <th>
                        产品编号
                    </th>
                    <th>
                        产品名称
                    </th>
                    <th>
                        生产企业
                    </th>
                    <th>
                        产品规格
                    </th>
                    <th>
                        产品型号
                    </th>
                    <th>
                        包装单位
                    </th>
                    <th>
                        产品数量
                    </th>
                    <th>
                        产品批号
                    </th>
                    <th>
                        生产日期
                    </th>
                    <th>
                        有效期
                    </th>
                    <th>
                        许可证号
                    </th>
                    <th>
                        注册证号
                    </th>
                    <th>
                        库房
                    </th>
                    <th>
                        库管
                    </th>
                    @if (Model.DataModel.CKID == 0)
                    {
                        <th type="del">
                            操作
                        </th>
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model.CKMXList != null)
                {
                    foreach (var item in Model.CKMXList)
                    {
                        <tr target="sid_user">
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPBH) ? item.T_YLCP.CPBH : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPMC) ? item.T_YLCP.CPMC : "")</td>
                            <td>@(item.T_YLCP != null && item.T_YLCP.T_SupQY1 != null && !string.IsNullOrEmpty(item.T_YLCP.T_SupQY1.SupMC) ? item.T_YLCP.T_SupQY1.SupMC : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPGG) ? item.T_YLCP.CPGG : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPXH) ? item.T_YLCP.CPXH : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPDW) ? item.T_YLCP.CPDW : "")</td>
                            <td>@item.CPNUM</td>
                            <td>@item.CPPH</td>
                            <td>@(item.CPSCRQ.HasValue ? item.CPSCRQ.Value.ToString("yyyy/MM/dd") : "")</td>
                            <td>@(item.CPYXQ.HasValue ? item.CPYXQ.Value.ToString("yyyy/MM/dd") : "")</td>
                            <td>@(item.T_YLCP != null && item.T_YLCP.T_SupQY1 != null && !string.IsNullOrEmpty(item.T_YLCP.T_SupQY1.SupXKZBH) ? item.T_YLCP.T_SupQY1.SupXKZBH : "")</td>
                            <td>@(item.T_YLCP != null && !string.IsNullOrEmpty(item.T_YLCP.CPZCZ) ? item.T_YLCP.CPZCZ : "")</td>
                            <td>@(item.T_CK != null && !string.IsNullOrEmpty(item.T_CK.CKMC) ? item.T_CK.CKMC : "")</td>
                            <td>@(item.T_CK != null && !string.IsNullOrEmpty(item.T_CK.CKGLY) ? item.T_CK.CKGLY : "")</td>
                            @if (Model.DataModel.CKID == 0)
                            {
                                <td>
                                    <a href="javascript:void(0)" name="@item.GUID" class="btnDel" onclick="deleteCKMX(this);">删除</a>
                                </td>
                            }
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</body>
</html>

MedicalApparatusManage/Views/T_CKMX/Index.cshtml
@model MedicalApparatusManage.Models.T_CKMXModels
@{
    Layout = null;
    int ckdid = Convert.ToInt32(ViewBag.CKDID);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>出库明细</title>
    @*<script src="~/Scripts/jquery-1.4.4.min.js"></script>
        <script src="~/Scripts/jquery.jqprint-0.3.js"></script>*@
    @*<script src="@Url.Content("~/Scripts/jquery-1.7.2.js")" type="text/javascript"></script>*@
    <script language="javascript">

        function prickd() {
            $("#printckd").jqprint();
        }
    </script>
</head>
<body>
    <div id="pageContent">
        <div class="pageHeader" style="hight: 80px;">
            @using (Html.BeginForm("Index", "T_CKMX", FormMethod.Post, new
        {
            name = "formSerachMA",
            id = "formSerachMA",
            onsubmit = "return navTabSearch(this);"

        }))
            {
                <div class="searchBar">
                    <table class="searchContent">
                        <tr>
                            <td>
                                开始日期:
                            </td>
                            <td>
                                @{ string strStart = Model.StartTime.HasValue ? Model.StartTime.Value.ToString("yyyy/MM/dd") : "";
                                 string strEnd = Model.EndTime.HasValue ? Model.EndTime.Value.ToString("yyyy/MM/dd") : "";
                                }
                                <input id="StartDate" name="StartTime" class="Wdate" type="text" value="@strStart"
                                       onfocus="WdatePicker({ dateFmt: 'yyyy/MM/dd', maxDate: '#F{$dp.$D(\'EndDate\')}' })" />
                            </td>
                            <td>
                                结束日期:
                            </td>
                            <td>
                                <input id="EndDate" name="EndTime" class="Wdate" type="text" value="@strEnd"
                                       onfocus="WdatePicker({ dateFmt: 'yyyy/MM/dd', minDate: '#F{$dp.$D(\'StartDate\')}' })" />
                            </td>

                            <td>
                                <ul>
                                    <li>
                                        <div class="buttonActive">
                                            <div class="buttonContent">
                                                <button type="submit" id="Button1" name="btnSerachOl">
                                                    检索
                                                </button>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    </table>
                </div>
            }

        </div>
        <div class="panelBar" id="EntLimitMenu">
            <ul class="toolBar">
                <li><a class="add" href="/T_CKMX/Save/@ckdid/Add" target="dialog" mask="true" title="新增" width="1050" height="500"><span>新增</span></a></li>
                <li> <a class="edit" href="/T_CKMX/Save/{sid_user}/Edit" target="dialog" mask="true" title="修改" width="1050" height="500"><span>修改</span></a></li>
                <li><a class="delete" href="/T_CKMX/Delete/{sid_user}" target="ajaxTodo" title="确定删除吗?" mask="true"><span>删除</span></a></li>
                <li><a class="icon" href="/T_CKMX/Save/{sid_user}/Details" target="dialog" mask="true" width="1050" height="500"><span>查看详情</span></a></li>
                <li><a class="icon" href="/T_CKMX/ExportExcel/@ckdid"><span>导出Excel</span></a></li>
                <li><input type="button" onclick="prickd()" value="打印" /></li>
            </ul>
        </div>
        <table width="100%" layouth="112" class="table" id="T_CKMXTable">
            <thead>
                <tr>
                    <th>
                        出库单
                    </th>
                    <th>
                        仓库名称
                    </th>
                    <th>
                        产品名称
                    </th>
                    <th>
                        产品规格
                    </th>
                    <th>
                        产品数量
                    </th>
                    <th>
                        备注
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.DataList)
                {
                    <tr target="sid_user" rel="@item.CKMID">
                        <td>@item.T_CKD.CKMC</td>
                        <td>@item.T_CK.CKMC</td>
                        <td>@item.T_YLCP.CPMC</td>
                        <td>@item.T_YLCP.CPGG</td>
                        <td>@item.CPNUM</td>
                        <td>@item.BZ</td>
                    </tr>
                }
            </tbody>
        </table>
        <form id="pagerForm" method="post" onsubmit="return navTabSearch(this);">
            <input type="hidden" name="pageNum" id="pageNum" />
            @Html.HiddenFor(m => m.pageSize, new { name = "numPerPage", id = "numPerPage" })
            <input type="hidden" name="totalCount" id="totalCount" />
            @Html.HiddenFor(m => m.SortCol, new { name = "SortCol_OP", id = "SortCol_OP" })
            @Html.HiddenFor(m => m.SortKey, new { name = "SortKey_OP", id = "SortKey_OP" })
            @Html.HiddenFor(m => m.StartTime, new { name = "StartTime" })
            @Html.HiddenFor(m => m.EndTime, new { name = "EndTime" })
            <input type="hidden" name="orderField" value="${param.orderField}" />
            <input type="hidden" name="orderDirection" value="${param.orderDirection}" />
        </form>
        <div class="panelBar">
            <div class="pages">
                <span style="width: 35px;">显示</span>
                @{
                    string[] sL = { "10", "20", "30", "50", "100", "500", "1000", "5000" };
                    List<SelectListItem>
                                list = new List<SelectListItem>
                                    ();
                    foreach (string s in sL)
                    {
                        list.Add(new SelectListItem { Text = s, Value = s });
                    }
                    @Html.DropDownListFor(m => m.pageSize, list, new { name = "numPerPage", id = "numPerPage", onchange = "navTabPageBreak({numPerPage:this.value});" });
                    <span>
                        条，共<label>@Model.resultCount</label>
                        条
                    </span>

                }
            </div>
            <div class="pagination" targettype="navTab" totalcount="@Model.resultCount"
                 numperpage="@Model.pageSize" pagenumshown="@Model.pagecount"
                 currentpage="@Model.currentPage">
            </div>
        </div>
    </div>
    <div id="printckd">@Html.Raw(ViewData["ParaStr"].ToString())</div>
        @*<div id="printckd"><table border="0" width="100%"><tr height="40"><td colspan="10" align="center" style='font-size:24px'><b>出库单</b></td></tr><tr height="40"><td colspan="8" align="left">购买单位：大华</td><td align="right">日期：2017-04-13</td><td align="right">单据编号：201704130141464670</td></tr></table><table border="1" width="100%"><tr height="30" align="center"><td>商品名称</td><td>规格</td><td>生产厂家</td><td>单位</td><td>数量</td><td>单价</td><td>金额</td><td>批号</td><td>生产日期</td><td>注册证号</td></tr><tr height="30" align="center"><td>器械</td><td>2016050101</td><td>ddd</td><td>盒</td><td>60</td><td>0</td><td>0</td><td></td><td></td><td></td></tr><tr height="30" align="center"><td>器械</td><td>2016050101</td><td>ddd</td><td>盒</td><td>11</td><td>0</td><td>0</td><td></td><td></td><td></td></tr><tr height="40" align="center"><td>合计：</td><td colspan="9">0</td></tr></table><table border="0" width="100%"><tr height="40" align="center"><td colspan="7" align="left">制单人：&nbsp;&nbsp</td><td align="right">审核人：&nbsp;&nbsp</td><td align="right">发货人：&nbsp;&nbsp</td><td align="center">销售员：&nbsp;&nbsp</td></tr></table></div>*@
</body>
</html>

MedicalApparatusManage/Views/T_CKMX/Save.cshtml
@model MedicalApparatusManage.Models.T_CKMXModels
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Save</title>
    <script type="text/javascript" language="javascript">
        $(function () {
            var tag = $("#Tag").val();
            if (tag == "Details") {
                $("form input").prop("readonly", true);
                $("#divSave").hide();
            }

            var cpid = $("#YLCP").val();
            if (cpid != "") {
                dropChange(cpid);
            }
        });
        function Save() {
            var elements = document.forms['formT_CKMX'];
            var bl = validateCallback(elements);
            if (bl) {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "/T_CKMX/Save",
                    data: $("#formT_CKMX").serializeArray(),
                    success: dialogAjaxDone
                });
            }
        };

        function dropChange(id) {
            if (id != "") {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "/T_YLCP/GetYLCP",
                    data: { cpid: id },
                    success: function (json) {
                        var tes = eval("(" + json + ")");
                        document.getElementById("cpgg").value = tes.CPGG;
                    },
                    error: function () {
                        alert("发生错误！");
                    }
                });
            }
        };
    </script>
</head>
<body>
    <div class="pageContent">
        <form id="formT_CKMX" method="post" onsubmit="return false;" class="pageForm required-validate-noalert">
            <div class="pageFormContent" layouth="58">
                @Html.HiddenFor(m => m.Tag, new { ID = "Tag", Name = "Tag" })
                @Html.HiddenFor(m => m.DataModel.CKMID, new { Name = "DataModel.CKMID" })

                <div class="unit">
                    <label>
                        出库单：
                    </label>
                    @Html.DropDownListFor(m => m.DataModel.CKDID, ViewData["CKD"] as SelectList,  new { style = "width:270px" })
                </div>
                <div class="unit">
                    <label>
                        仓库：
                    </label>
                    @Html.DropDownListFor(m => m.DataModel.CKID, ViewData["CK"] as SelectList, new { style = "width:270px" })
                </div>
                <div class="unit">
                    <label>
                        产品名称：
                    </label>
                    @Html.DropDownListFor(m => m.DataModel.CPID, ViewData["YLCP"] as SelectList, new { ID = "YLCP", style = "width:270px", onchange = "dropChange(this.value)" })
                </div>
                <div class="unit">
                    <label>
                        产品规格：
                    </label>
                    <input type="text" id="cpgg" style="width:270px" readonly="readonly" value="" />
                </div>
                <div class="unit">
                    <label>
                        产品数量：
                    </label>
                    @Html.TextBoxFor(m => m.DataModel.CPNUM, new { name = "CPNUM", style = "width:260px" })
                </div>
                <div class="unit">
                    <label>
                        备注：
                    </label>
                    @Html.TextAreaFor(m => m.DataModel.BZ, new { name = "BZ", style = "width:260px;height:120px" })
                </div>
            </div>
            <div class="formBar">
                <ul>
                    <li>
                        <div class="button" id="divSave">
                            <div class="buttonContent">
                                <button value="保存" onclick="Save();">
                                    保存
                                </button>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="button">
                            <div class="buttonContent">
                                <button value="取消" class="close">
                                    取消
                                </button>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</body>
</html>