MedicalApparatusManage/Controllers/T_HTController.cs
using MedicalApparatusManage.Domain;
using MedicalApparatusManage.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MedicalApparatusManage.Controllers
{
    public class T_HTController : Controller
    {
        public int resultCount = 0; // 总条数 

        [CheckLogin()]
        public ActionResult Index(T_HTModels evalModel)
        {
            try
            {
                SysUser UserModel = Session["UserModel"] as SysUser;
                ViewData["shUserId"] = UserModel.UserId;
                evalModel.currentPage = int.Parse(Request["pageNum"].ToString());
            }
            catch { }
            string order = "";
            try
            {
                order = Request["orderField"].ToString();
            }
            catch { }

            if (order.Trim() == "${param.orderField}")
            {
                order = "";
            }
            int pagesize = Convert.ToInt32(evalModel.pageSize);
            int pagecount = Convert.ToInt32(evalModel.pagecount);
            int currentPage = Convert.ToInt32(evalModel.currentPage);
            evalModel.DataModel = evalModel.DataModel ?? new T_HT();

            if (Request["strHTCode"] != null)
            {
                string str = Request["strHTCode"].ToString();
                if(!String.IsNullOrEmpty(str))
                {
                    evalModel.DataModel.HTBH = str.Trim();
                }
            }

            if (Request["strHTMC"] != null)
            {
                string str = Request["strHTMC"].ToString();
                if (!String.IsNullOrEmpty(str))
                {
                    evalModel.DataModel.HTMC = str.Trim();
                }
            }

            evalModel.DataList = T_HTDomain.GetInstance().PageT_HT(evalModel.DataModel, evalModel.StartTime, evalModel.EndTime, currentPage, pagesize, out pagecount, out resultCount);
            evalModel.resultCount = resultCount;
            return View("~/Views/T_HT/Index.cshtml", evalModel);
        }

        [CheckLogin()]
        public ActionResult Save(System.Int32 id, string tag)
        {

            //加载购买商商企业列表
            //T_CGDModels cgdQymode = new T_CGDModels();

            //cgdQymode.DataModel = cgdQymode.DataModel ?? new T_CGD();

            //cgdQymode.DataList = T_CGDDomain.GetInstance().GetAllT_CGD(cgdQymode.DataModel);

            //ViewData["CGD"] = new SelectList(cgdQymode.DataList, "CGID", "CGDMC");

            //加载企业列表
            T_SupQYModels supmode = new T_SupQYModels();

            supmode.DataModel = supmode.DataModel ?? new T_SupQY();

            supmode.DataList = T_SupQYDomain.GetInstance().GetAllT_SupQY(supmode.DataModel).Where(p => p.SupStatus == 1).ToList();

            ViewData["SupID"] = new SelectList(supmode.DataList, "SupID", "SupMC");

            T_HTModels model = new T_HTModels();
            model.DataModel = new T_HT();
            if (id != 0)
            {
                model.DataModel = T_HTDomain.GetInstance().GetModelById(id);
            }
            model.Tag = tag;
            return View("~/Views/T_HT/Save.cshtml", model);
        }

        [HttpPost]
        [CheckLogin()]
        public void Save(T_HTModels model)
        {
            int result = 0;
            try
            {
                if (model.Tag == "Add")
                {
                    model.DataModel.SHJG = 0;
                    result = T_HTDomain.GetInstance().AddModel(model.DataModel);
                }
                else if (model.Tag == "Edit")
                {
                    result = T_HTDomain.GetInstance().UpdateModel(model.DataModel, model.DataModel.HTID);
                }

            }
            catch { }
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"closeCurrentReloadTab\",\"forwardUrl\":\"/T_HT/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }

        [CheckLogin()]
        public ActionResult HTSPIndex(System.Int32 id, string tag)
        {
            T_HTModels model = new T_HTModels();
            model.DataModel = new T_HT();
            if (id != 0)
            {
                model.DataModel = T_HTDomain.GetInstance().GetModelById(id);
                //加载企业列表
                T_SupQYModels supmode = new T_SupQYModels();

                supmode.DataModel = supmode.DataModel ?? new T_SupQY();

                supmode.DataList = T_SupQYDomain.GetInstance().GetAllT_SupQY(supmode.DataModel).Where(p => p.SupStatus == 1).ToList();

                ViewData["SupID"] = new SelectList(supmode.DataList, "SupID", "SupMC");
            }
            model.Tag = tag;
            return View("~/Views/T_HT/HTSPIndex.cshtml", model);
        }

        [HttpPost]
        [CheckLogin()]
        public void through(T_HTModels model, string id)
        {
            int result = 0;
            try
            {
                Int32 xsdid = model.DataModel.HTID;
                T_HT temp = T_HTDomain.GetInstance().GetModelById(xsdid);

                model.DataModel.HTQDDWID = temp.HTQDDWID;

                if (id == "1")
                {
                    model.DataModel.SHJG = 1;
                }
                else
                {
                    model.DataModel.SHJG = 2;
                }
                result = T_HTDomain.GetInstance().UpdateModel(model.DataModel, model.DataModel.HTID);
            }
            catch { }
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"closeCurrentReloadTab\",\"forwardUrl\":\"/T_HT/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }

        [CheckLogin()]
        public ActionResult Upload(HttpPostedFileBase Filedata)
        {
            string uptype = Request["uptype"].ToString();
            string uploadDate = DateTime.Now.ToString("yyyymmddhhmmss");
            // 如果没有上传文件
            if (Filedata == null ||
                string.IsNullOrEmpty(Filedata.FileName) ||
                Filedata.ContentLength == 0)
            {
                return this.HttpNotFound();
            }
            string filename = uploadDate + Path.GetFileName(Filedata.FileName);

            //目录
            string directory;
            if (uptype == "0")
            {
                directory = Path.Combine(Server.MapPath("~/UploadFiles/"), "采购合同附件");
            }
            else
            {
                directory = Path.Combine(Server.MapPath("~/UploadFiles/"), "采购质量协议");
            }

            //上传文件记录上传到数据库中
            //上传顺序：先数据库中增加记录成功，再上传文件
            var fileUpload = new UploadFile();
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            string path = directory + "\\" + filename;
            Filedata.SaveAs(path);
            return Json(new { status = "OK", filename = filename });
        }

        [HttpPost]
        [CheckLogin()]
        public void Delete(System.Int32 id)
        {
            T_HTModels model = new T_HTModels();
            model.DataModel = new T_HT();
            if (id != 0)
            {
                model.DataModel = T_HTDomain.GetInstance().GetModelById(id);
            }
            string filePath = Path.Combine(Server.MapPath("~/UploadFiles/"), "采购合同附件", model.DataModel.HTFJ);
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }
            string filePath1 = Path.Combine(Server.MapPath("~/UploadFiles/"), "采购质量协议", model.DataModel.ZLXY);
            if (System.IO.File.Exists(filePath1))
            {
                System.IO.File.Delete(filePath1);
            }
            int result = T_HTDomain.GetInstance().DeleteModelById(id);
            Response.ContentType = "text/json";
            if (result > 0)
                Response.Write("{\"statusCode\":\"200\", \"message\":\"操作成功\",\"callbackType\":\"forward\",\"forwardUrl\":\"/T_HT/Index\"}");
            else
                Response.Write("{\"statusCode\":\"300\", \"message\":\"操作失败\"}");
        }
    }
}

MedicalApparatusManage/Views/T_HT/HTSPIndex.cshtml
@model MedicalApparatusManage.Models.T_HTModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Audit</title>
    <script type="text/javascript" language="javascript">
        $(function () {
            var tag = $("#Tag").val();
            if (tag == "Details") {
                $("form input").prop("readonly", true);
                $("#divSave").hide();
            }
        });
        function through(type) {
            var elements = document.forms['formHTSPIndex'];
            var bl = validateCallback(elements);
            if (bl) {
                $.ajax({
                    type: "post",
                    dataType: "json",
                    url: "/T_HT/through/" + type,
                    data: $("#formHTSPIndex").serializeArray(),
                    success: dialogAjaxDone
                });
            }
        };
    </script>
</head>
<body>
    <div>
        <form id="formHTSPIndex" method="post" onsubmit="return false;" class="pageForm required-validate-noalert">
            <div style="width: 100%;" class="pageFormContent" layouth="58">
                <div style="width: 50%; float: left;">
                    <fieldset style=" height:100%;">
                        <legend>采购单</legend>
                        <div class="unit">
                            <label>
                                采购单名称：
                            </label>
                            @Html.TextBoxFor(m => m.CGDmodel.CGDMC, new { name = "CGDMC", @readonly = "readonly"})
                        </div>
                        <div class="unit">
                            <label>
                                采购人：
                            </label>
                            @Html.TextBoxFor(m => m.CGDmodel.CGPERSON, new { name = "CGPERSON", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                采购日期：
                            </label>
                            @Html.TextBoxFor(m => m.CGDmodel.CGRQ, new { name = "CGRQ", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                检验员：
                            </label>
                            @Html.TextBoxFor(m => m.CGDmodel.JYPERSON, new { name = "JYPERSON", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                检验时间：
                            </label>
                            @Html.TextBoxFor(m => m.CGDmodel.JYQR, new { name = "JYQR", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                是否合格：
                            </label>
                            @{
                                List<SelectListItem> ishgList = new List<SelectListItem>();

                                ishgList.Add(new SelectListItem { Text = "是", Value = "1" });
                                ishgList.Add(new SelectListItem { Text = "否", Value = "0" });

                                @Html.DropDownListFor(m => m.CGDmodel.ISHG, ishgList, "请选择", new { style = "width:270px", disabled = "disabled" })
                            }
                        </div>
                        <div class="unit">
                            <label>
                                申请人：
                            </label>
                            @Html.TextBoxFor(m => m.CGDmodel.SQPERSON, new { name = "SQPERSON", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                申请日期：
                            </label>
                            @Html.TextBoxFor(m => m.CGDmodel.SQRQ, new { name = "SQRQ", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                是否到货：
                            </label>
                            @{
                                List<SelectListItem> isdhList = new List<SelectListItem>();

                                isdhList.Add(new SelectListItem { Text = "是", Value = "1" });
                                isdhList.Add(new SelectListItem { Text = "否", Value = "0" });

                                @Html.DropDownListFor(m => m.CGDmodel.ISCG, isdhList, "请选择", new { style = "width:270px", disabled = "disabled" })
                            }
                        </div>
                    </fieldset>
                </div>
                @Html.HiddenFor(m => m.Tag, new { ID = "Tag", Name = "Tag" })
                @Html.HiddenFor(m => m.DataModel.HTID, new { Name = "DataModel.HTID" })
                <div style="width: 50%; float: right;">
                    <fieldset>
                        <legend>合同信息</legend>
                        @*<div class="unit">
                            <label>
                                采购单名称：
                            </label>
                            @Html.TextBoxFor(m => m.DataModel.CGDID, new { name = "CGDID" })
                        </div>*@
                        <div class="unit">
                            <label>
                                合同编号：
                            </label>
                            @Html.TextBoxFor(m => m.DataModel.HTBH, new { name = "HTBH", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                合同名称：
                            </label>
                            @Html.TextBoxFor(m => m.DataModel.HTMC, new { name = "HTMC", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                合同签订单位：
                            </label>
                           @Html.DropDownListFor(m => m.DataModel.HTQDDWID, ViewData["SupID"] as SelectList, "请选择", new { style = "width:270px", disabled = "disabled" })
                        </div>
                        <div class="unit">
                            <label>
                                合同申请人：
                            </label>
                            @Html.TextBoxFor(m => m.DataModel.HTSQR, new { name = "HTSQR", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                申请时间：
                            </label>
                            @Html.TextBoxFor(m => m.DataModel.SQSJ, new { name = "SQSJ", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                合同附件：
                            </label>
                            <div>
                                <a href="~/UploadFiles/采购合同附件/@ViewData["HTFJ"]" target="_blank">@ViewData["HTFJ"]</a>
                            </div>
                        </div>
                        <div class="unit">
                            <label>
                                质量协议：
                            </label>
                            <div>
                                <a href="~/UploadFiles/质量协议/@ViewData["ZLXY"]" target="_blank">@ViewData["ZLXY"]</a>
                            </div>
                        </div>
                        <div class="unit">
                            <label>
                                审核人：
                            </label>
                            @Html.TextBoxFor(m => m.DataModel.SHR, new { name = "SHR", @readonly = "readonly" })
                        </div>
                        <div class="unit">
                            <label>
                                审核时间：
                            </label>
                            @Html.TextBoxFor(m => m.DataModel.SHSJ, new { name = "SHSJ", @readonly = "readonly" })
                        </div>
                        @*<div class="unit">
                                <label>
                                    备注：
                                </label>
                                @Html.TextBoxFor(m => m.DataModel.BZ, new { name = "BZ" })
                            </div>*@
                        @*<div class="unit">
                                <label>
                                    审核结果：
                                </label>
                                @Html.TextBoxFor(m => m.DataModel.SHJG, new { name = "SHJG" })
                            </div>*@
                    </fieldset>
                </div>
            </div>
            <div class="formBar">
                <ul>
                    <li>
                        <div class="button" id="divSave">
                            <div class="buttonContent">
                                <button value="通过" onclick="through(1);">
                                    通过
                                </button>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="button" id="divSave">
                            <div class="buttonContent">
                                <button value="不通过" onclick="through(2);">
                                    不通过
                                </button>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="button">
                            <div class="buttonContent">
                                <button value="取消" class="close">
                                    取消
                                </button>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</body>
</html>

MedicalApparatusManage/Views/T_HT/Index.cshtml
@model MedicalApparatusManage.Models.T_HTModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>合同管理</title>
</head>
<body>
    <div id="pageContent">
        <div class="pageHeader" style="hight: 80px;">
            @using (Html.BeginForm("Index", "T_HT", FormMethod.Post, new
            {
                name = "formSerachMA",
                id = "formSerachMA",
                onsubmit = "return navTabSearch(this);"

            }))
            {
                <div class="searchBar">
                    <table class="searchContent">
                        <tr>
                            <td>
                                合同编号:
                            </td>
                            <td>
                                @Html.TextBox("strHTCode")
                            </td>
                            <td>
                                合同名称:
                            </td>
                            <td>
                                @Html.TextBox("strHTMC")
                            </td>

                            <td>
                                <ul>
                                    <li>
                                        <div class="buttonActive">
                                            <div class="buttonContent">
                                                <button type="submit" id="Button1" name="btnSerachOl">
                                                    检索
                                                </button>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    </table>
                </div>
                                    }
        </div>
        <div class="panelBar" id="EntLimitMenu">
            <ul class="toolBar">
                <li><a class="add" href="/T_HT/Save/0/Add" target="dialog"  mask="true" title="新增" width="1050" height="500"><span>新增</span></a></li>
                <li> <a class="edit" href="/T_HT/Save/{sid_user}/Edit" target="dialog" mask="true" title="修改" width="1050" height="500"><span>修改</span></a></li>
                <li><a class="delete" href="/T_HT/Delete/{sid_user}" target="ajaxTodo" title="确定删除吗?" mask="true"><span>删除</span></a></li>
                <li><a class="icon" href="/T_HT/Save/{sid_user}/Details" target="dialog"  mask="true" width="1050" height="500"><span>查看详情</span></a></li>
                @if (ViewData["shUserId"].ToString() == "1" || ViewData["shUserId"].ToString() == "2")
                {
                    <li> <a class="edit" href="/T_HT/HTSPIndex/{sid_user}" target="dialog" mask="true" title="审核" width="1050" height="580"><span>审核</span></a></li>
                }
            </ul>
        </div>
        <table width="100%" layouth="112" class="table" id="T_HTTable">
           <thead>
                <tr>
                    <th>
                        合同编号
                    </th>
                    <th>
                        合同名称
                    </th>
                    <th>
                        合同签订单位
                    </th>
                    @*<th>
                        采购
                    </th>*@
                    <th>
                        合同申请人
                    </th>
                    <th>
                        申请时间
                    </th>
                    <th>
                        合同附件
                    </th>
                    <th>
                        质量协议
                    </th>
                    <th>
                        备注
                    </th>
                    <th>
                        审核人
                    </th>
                    <th>
                        审核时间
                    </th>
                    <th>
                        审核结果
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.DataList)
                {
                    <tr target="sid_user" rel="@item.HTID">
                        <td>@item.HTBH</td>
                        <td>@item.HTMC</td>
                        <td>@item.T_SupQY.SupMC</td>
                        @*<td>@item.T_CGD.CGDMC</td>*@
                        <td>@item.HTSQR</td>
                        <td>@item.SQSJ</td>
                        <td><a href="~/UploadFiles/采购合同附件/@item.HTFJ" target="_blank">@item.HTFJ</a></td>
                        <td><a href="~/UploadFiles/采购质量协议/@item.ZLXY" target="_blank">@item.ZLXY</a></td>
                        <td>@item.BZ</td>
                        <td>@item.SHR</td>
                        <td>@item.SHSJ</td>
                        @if (item.SHJG == 0)
                        {
                            <td>待审批</td>
                        }
                        else if (item.SHJG == 1)
                        {
                            <td>已审批</td>
                        }
                        else if (item.SHJG == 2)
                        {
                            <td>审批未通过</td>
                        }
                    </tr>
                }
            </tbody>
        </table>
        <form id="pagerForm" method="post" onsubmit="return navTabSearch(this);">
            <input type="hidden" name="pageNum" id="pageNum" />
            @Html.HiddenFor(m => m.pageSize, new { name = "numPerPage", id = "numPerPage" })
            <input type="hidden" name="totalCount" id="totalCount" />
            @Html.HiddenFor(m => m.SortCol, new { name = "SortCol_OP", id = "SortCol_OP" })
            @Html.HiddenFor(m => m.SortKey, new { name = "SortKey_OP", id = "SortKey_OP" })
            @Html.HiddenFor(m => m.StartTime, new { name = "StartTime" })
            @Html.HiddenFor(m => m.EndTime, new { name = "EndTime" })
            <input type="hidden" name="orderField" value="${param.orderField}" />
            <input type="hidden" name="orderDirection" value="${param.orderDirection}" />
        </form>
        <div class="panelBar">
            <div class="pages">
                <span style="width: 35px;">显示</span>
                @{
                    string[] sL = { "10", "20", "30", "50", "100", "500", "1000", "5000" };
                    List<SelectListItem>
                                list = new List<SelectListItem>
                                    ();
                    foreach (string s in sL)
                    {
                        list.Add(new SelectListItem { Text = s, Value = s });
                    }
                    @Html.DropDownListFor(m => m.pageSize, list, new { name = "numPerPage", id = "numPerPage", onchange = "navTabPageBreak({numPerPage:this.value});" });
                    <span>
                        条，共<label>@Model.resultCount</label>
                        条
                    </span>

                }
            </div>
            <div class="pagination" targettype="navTab" totalcount="@Model.resultCount"
                 numperpage="@Model.pageSize" pagenumshown="@Model.pagecount"
                 currentpage="@Model.currentPage">
            </div>
        </div>
    </div>
</body>
</html>